/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-background': '#dae2fd',
        'on-surface-variant': '#bcc9c6',
        'primary-fixed-dim': '#6bd8cb',
        'secondary-container': '#ec6a06',
        'tertiary': '#ffb3ad',
        'inverse-surface': '#dae2fd',
        'outline-variant': '#3d4947',
        'on-tertiary-fixed': '#410004',
        'secondary-fixed-dim': '#ffb690',
        'inverse-primary': '#006a61',
        'primary': '#6bd8cb',
        'outline': '#879391',
        'on-surface': '#dae2fd',
        'on-secondary': '#552100',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb3ad',
        'secondary-fixed': '#ffdbca',
        'on-tertiary': '#68000a',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'error': '#ffb4ab',
        'tertiary-fixed': '#ffdad7',
        'on-tertiary-fixed-variant': '#930013',
        'primary-fixed': '#89f5e7',
        'surface-dim': '#0b1326',
        'surface-container-low': '#131b2e',
        'on-secondary-fixed-variant': '#783200',
        'background': '#0b1326',
        'primary-container': '#29a195',
        'surface-bright': '#31394d',
        'inverse-on-surface': '#283044',
        'secondary': '#ffb690',
        'on-secondary-container': '#4a1c00',
        'surface-container-lowest': '#060e20',
        'on-tertiary-container': '#5c0008',
        'on-primary': '#003732',
        'tertiary-container': '#ff5451',
        'on-secondary-fixed': '#341100',
        'on-primary-fixed-variant': '#005049',
        'surface-variant': '#2d3449',
        'surface': '#0b1326',
        'error-container': '#93000a',
        'on-primary-fixed': '#00201d',
        'surface-tint': '#6bd8cb',
        'on-primary-container': '#00302b',
        'surface-container-highest': '#2d3449',
        'on-error': '#690005',
      },
      fontFamily: {
        'sans': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'inter': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'grotesk': ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-vitals': ['48px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'metric-unit': ['11px', { lineHeight: '12px', fontWeight: '500' }],
      },
      spacing: {
        'md': '16px',
        'margin': '24px',
        'sm': '8px',
        'unit': '4px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '16px',
        'xs': '4px',
      },
    },
  },
  plugins: [],
}
